# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages

matrix:
  include:
    - os: linux
      sudo: false
      r: oldrel
    - os: linux
      sudo: false
      r: release
    - os: linux
      sudo: false
      r: devel
    - os: osx
      disable_homebrew: true
      r: oldrel
    - os: osx
      disable_homebrew: true
      r: release
    - os: osx
      disable_homebrew: true
      osx_image: xcode8
      r: devel
      
warnings_are_errors: true