# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eho <- function(param, numbuys, numsells) {
    .Call('pinbasic_eho', PACKAGE = 'pinbasic', param, numbuys, numsells)
}

linke <- function(param, numbuys, numsells) {
    .Call('pinbasic_linke', PACKAGE = 'pinbasic', param, numbuys, numsells)
}

simBS <- function(param, ndays) {
    .Call('pinbasic_simBS', PACKAGE = 'pinbasic', param, ndays)
}

